apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata: 
   name: eks-fargate-cluster
   region: ap-southeast-1
   
fargateProfiles:
   - name: fp-default
     selectors:
        - namespace: default
        - namespace: kube-system