apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
   name: mtabishk-ekscluster
   region: ap-south-1
  
nodeGroups:
   - name: nodegroup1
     desiredCapacity: 2
     minSize: 2
     maxSize: 5
     instanceType: t2.micro
     ssh:
      publicKeyName: mtabishkawskey 
   
   - name: nodegroup2-mixed
     minSize: 2
     maxSize: 5
     instancesDistribution:
       maxPrice: 0.020
       instanceTypes: ["t2.small", "t3.medium"]
       onDemandBaseCapacity: 0
       onDemandPercentageAboveBaseCapacity: 50
       spotInstancePools: 2
     ssh:
      publicKeyName: mtabishkawskey 
